version: '3.5'
services:

  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  database_data:
